fixed some bugs, includeded files and md5 checksums for downloads.   tested with modified logstash charm, but need to update that to do relationships properly.

diff --git a/hooks/install b/hooks/install
--- a/hooks/install
+++ b/hooks/install
@@ -1,12 +1,9 @@
-#!/bin/sh
+#!/bin/bash
 # Adapted from http://www.elasticsearch.org/tutorials/2010/07/01/setting-up-elasticsearch.html
 
-VERSION=$(config-get version)
-CLUSTER_NAME=$(config-get cluster-name)
-BOOTSTRAP_CLASS=$(config-get bootstrap-class)
-ACCESS_KEY=$(config-get access-key)
-SECRET_KEY=$(config-get secret-key)
-REGION=$(config-get region)
+set -eux # -x for verbose logging to juju debug-log
+HOME=`dirname $0`
+. $HOME/common.sh
 
 juju-log "Check if we've installed elasticsearch before"
 
@@ -14,20 +11,49 @@ if [ ! -f "/opt/elasticsearch-$VERSION/bin/elasticsearch" ]; then
 	juju-log "Installing OpenJDK"
 	apt-get install -y default-jre-headless wget
 
-  cd /opt
+  juju-log "Downloading elasticsearch"
 
-	juju-log "Downloading elasticsearch"
-  wget -q "https://github.com/downloads/elasticsearch/elasticsearch/elasticsearch-$VERSION.tar.gz"
-  tar xzvf elasticsearch-$VERSION.tar.gz
-  ln -s elasticsearch-$VERSION elasticsearch
-  rm elasticsearch-$VERSION.tar.gz
+  # Check if a local copy of the jar exists
+  if [ -f $HOME/../files/charm/elasticsearch-$VERSION.tar.gz ]
+  then
+    juju-log "elasticsearch binary found local,copy to /tmp"
+    install -o root -g root -m 0644 $HOME/../files/charm/elasticsearch-$VERSION.tar.gz /tmp/elasticsearch-$VERSION.tar.gz
+  else
+    # Download and checksum
+    juju-log "elasticsearch wrapper binary not found local ... download"
+    wget -q -O /tmp/elasticsearch-$VERSION.tar.gz "${DOWNLOADURL}/elasticsearch-$VERSION.tar.gz"
+    if [[ $(md5sum "/tmp/elasticsearch-$VERSION.tar.gz" | cut -d " " -f 1) != ${CHECKSUM} ]]; then
+      juju-log --log-level CRITICAL "Checksum of elasticsearch-$VERSION.tar.gz failed"
+      exit 1
+    fi
+  fi
 
 	juju-log "Installing service wrapper"
-  wget -q http://github.com/elasticsearch/elasticsearch-servicewrapper/tarball/master -O- | tar -xz
+  if [ -f $HOME/../files/charm/es-wrapper.tar.gz ]
+  then
+    juju-log "elasticsearch wrapper binary found local"
+    install -o root -g root -m 0644 $HOME/../files/charm/es-wrapper.tar.gz /tmp/es-wrapper.tar.gz
+   else
+    # Download and checksum
+    juju-log "elasticsearch wrapper binary not found local ... download"
+    wget  -q -O /tmp/es-wrapper.tar.gz "http://github.com/elasticsearch/elasticsearch-servicewrapper/tarball/master"
+    if [[ $(md5sum "/tmp/es-wrapper.tar.gz" | cut -d " " -f 1) != ${CHECKSUMWRAPPER} ]]; then
+      juju-log --log-level CRITICAL "Checksum of es-wrapper.tar.gz failed"
+      exit 1
+    fi
+  fi
+  juju-log "untar elasticsearch"
+  cd /opt
+  tar xzvf /tmp/elasticsearch-$VERSION.tar.gz
+  ln -s elasticsearch-$VERSION elasticsearch
+  rm /tmp/elasticsearch-$VERSION.tar.gz
+  juju-log "untar elasticsearch service wrapper"
+  tar xzvf /tmp/es-wrapper.tar.gz
+  rm /tmp/es-wrapper.tar.gz
   mv *servicewrapper*/service elasticsearch/bin/
   rm -Rf *servicewrapper*
 
-  cd elasticsearch
+  cd /opt/elasticsearch
 
   juju-log "Setup elasticsearch as a service"
   bin/service/elasticsearch install
@@ -37,6 +63,7 @@ if [ ! -f "/opt/elasticsearch-$VERSION/bin/elasticsearch" ]; then
   sed -i "/wrapper.app.parameter.1/c wrapper.app.parameter.1=$BOOTSTRAP_CLASS" bin/service/elasticsearch.conf
   sed -i "/cluster.name:/ c\cluster.name: $CLUSTER_NAME" config/elasticsearch.yml
 
+  # If Amazon install some magic stuff to allow auto-discovery of other ES nodes.
   if [ ! -z "$ACCESS_KEY" ] && [ ! -z "$SECRET_KEY" ]; then
     juju-log "Install elasticsearch aws plugin"
     bin/plugin -install elasticsearch/elasticsearch-cloud-aws/1.4.0 > /dev/null
